# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2086b3a05dc349b9af64e76dfcb10965f1024dd8aac18b3114c0179ac6a3c226f44e0589933c256a1ec3e8ecdfdfd322a30672165b73f21b716a6ebf7e78b92

test:
  secret_key_base: ec3c0c4091bb3c0adcb8c66c6773223b0a0281e2b5fc1e9c721086d7439b0540ca45fc4d2536e693a0bf8e9c30751954f3f357c5397203d31cfa157051fc36e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
